# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'place42' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for place42
  pod 'GoogleMaps', '~> 3.7.0'

end
